# Translations template for keystone.
# Copyright (C) 2016 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: keystone 9.0.0.0b2.dev256\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2016-01-18 06:05+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: keystone/exception.py:83
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:92
#, python-format
msgid "Cannot create an endpoint with an invalid URL: %(url)s"
msgstr ""

#: keystone/exception.py:99
#, python-format
msgid "%(detail)s"
msgstr ""

#: keystone/exception.py:103
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""

#: keystone/exception.py:112
msgid ""
"The 'expires_at' must not be before now. The server could not comply with"
" the request since it is either malformed or otherwise incorrect. The "
"client is assumed to be in error."
msgstr ""

#: keystone/exception.py:121
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""

#: keystone/exception.py:127
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:137
#, python-format
msgid ""
"The specified parent region %(parent_region_id)s would create a circular "
"region hierarchy."
msgstr ""

#: keystone/exception.py:144
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server "
"could not comply with the request because the password is invalid."
msgstr ""

#: keystone/exception.py:152
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions "
"have associated endpoints."
msgstr ""

#: keystone/exception.py:159
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:171
msgid "(Disable insecure_debug mode to suppress these details.)"
msgstr ""

#: keystone/exception.py:181
#, python-format
msgid "%(message)s %(amendment)s"
msgstr ""

#: keystone/exception.py:189
msgid "The request you have made requires authentication."
msgstr ""

#: keystone/exception.py:195
msgid "Authentication plugin error."
msgstr ""

#: keystone/exception.py:203
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:208
msgid "Attempted to authenticate with an unsupported method."
msgstr ""

#: keystone/exception.py:216
msgid "Additional authentications steps required."
msgstr ""

#: keystone/exception.py:224
msgid "You are not authorized to perform the requested action."
msgstr ""

#: keystone/exception.py:231
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr ""

#: keystone/exception.py:236
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target "
"%(target)s"
msgstr ""

#: keystone/exception.py:241
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in "
"question is %(group_id)s, user is %(user_id)s"
msgstr ""

#: keystone/exception.py:247
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service "
"or Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, "
"Service: %(service_id)s, Region: %(region_id)s"
msgstr ""

#: keystone/exception.py:254
#, python-format
msgid "Invalid domain specific configuration: %(reason)s"
msgstr ""

#: keystone/exception.py:258
#, python-format
msgid "Could not find: %(target)s"
msgstr ""

#: keystone/exception.py:264
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr ""

#: keystone/exception.py:272
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr ""

#: keystone/exception.py:277
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr ""

#: keystone/exception.py:281
msgid "Could not find policy association"
msgstr ""

#: keystone/exception.py:285
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr ""

#: keystone/exception.py:289
#, python-format
msgid ""
"Could not find role assignment with role: %(role_id)s, user or group: "
"%(actor_id)s, project or domain: %(target_id)s"
msgstr ""

#: keystone/exception.py:295
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr ""

#: keystone/exception.py:299
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr ""

#: keystone/exception.py:303
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:307
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr ""

#: keystone/exception.py:311
#, python-format
msgid "Cannot create project with parent: %(project_id)s"
msgstr ""

#: keystone/exception.py:315
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr ""

#: keystone/exception.py:319
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr ""

#: keystone/exception.py:323
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr ""

#: keystone/exception.py:327
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr ""

#: keystone/exception.py:331
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:335
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:339
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr ""

#: keystone/exception.py:343
#, python-format
msgid "Could not find version: %(version)s"
msgstr ""

#: keystone/exception.py:347
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr ""

#: keystone/exception.py:351
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr ""

#: keystone/exception.py:355
#, python-format
msgid "Could not find Service Provider: %(sp_id)s"
msgstr ""

#: keystone/exception.py:359
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:370
#, python-format
msgid ""
"Could not find %(group_or_option)s in domain configuration for domain "
"%(domain_id)s"
msgstr ""

#: keystone/exception.py:382
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr ""

#: keystone/exception.py:391
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:394
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""

#: keystone/exception.py:412
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr ""

#: keystone/exception.py:417
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:423
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""

#: keystone/exception.py:428
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:433
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr ""

#: keystone/exception.py:437
#, python-format
msgid ""
"Unexpected combination of grant attributes - User: %(user_id)s, Group: "
"%(group_id)s, Project: %(project_id)s, Domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:444
msgid "The action you have requested has not been implemented."
msgstr ""

#: keystone/exception.py:451
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:458
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:463
msgid ""
"No encryption keys found; run keystone-manage fernet_setup to bootstrap "
"one."
msgstr ""

#: keystone/exception.py:468
#, python-format
msgid ""
"The Keystone domain-specific configuration has specified more than one "
"SQL driver (only one is permitted): %(source)s."
msgstr ""

#: keystone/exception.py:475
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/exception.py:482
msgid "Token version is unrecognizable or unsupported."
msgstr ""

#: keystone/exception.py:487
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not "
"have xmlsec1 installed, or this is the result of misconfiguration. Reason"
" %(reason)s"
msgstr ""

#: keystone/exception.py:494
msgid ""
"No Authorization headers found, cannot proceed with OAuth related calls, "
"if running under HTTPd or Apache, ensure WSGIPassAuthorization is set to "
"On."
msgstr ""

#: keystone/exception.py:501
#, python-format
msgid ""
"Could not determine Identity Provider ID. The configuration option "
"%(issuer_attribute)s was not found in the request environment."
msgstr ""

#: keystone/exception.py:509
#, python-format
msgid ""
"The %s extension has been moved into keystone core and as such its "
"migrations are maintained by the main keystone database control. Use the "
"command: keystone-manage db_sync"
msgstr ""

#: keystone/exception.py:517
#, python-format
msgid "%(driver)s is not supported driver version"
msgstr ""

#: keystone/notifications.py:275
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:284
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/assignment/controllers.py:99 keystone/identity/controllers.py:71
#: keystone/resource/controllers.py:85
msgid "Name field is required and cannot be empty"
msgstr ""

#: keystone/assignment/controllers.py:145
#: keystone/assignment/controllers.py:162
#: keystone/assignment/controllers.py:181
msgid "User roles not supported: tenant_id required"
msgstr ""

#: keystone/assignment/controllers.py:345
#: keystone/assignment/controllers.py:585
msgid "Specify a domain or project, not both"
msgstr ""

#: keystone/assignment/controllers.py:348
msgid "Specify one of domain or project"
msgstr ""

#: keystone/assignment/controllers.py:353
#: keystone/assignment/controllers.py:590
msgid "Specify a user or group, not both"
msgstr ""

#: keystone/assignment/controllers.py:356
msgid "Specify one of user or group"
msgstr ""

#: keystone/assignment/controllers.py:574
msgid "Combining effective and group filter will always result in an empty list."
msgstr ""

#: keystone/assignment/controllers.py:579
msgid ""
"Combining effective, domain and inherited filters will always result in "
"an empty list."
msgstr ""

#: keystone/assignment/controllers.py:678
msgid "scope.project.id must be specified if include_subtree is also specified"
msgstr ""

#: keystone/assignment/core.py:139
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/core.py:843
#, python-format
msgid "Project (%s)"
msgstr ""

#: keystone/assignment/core.py:845
#, python-format
msgid "Domain (%s)"
msgstr ""

#: keystone/assignment/core.py:847
msgid "Unknown Target"
msgstr ""

#: keystone/assignment/V8_backends/sql.py:287
#: keystone/assignment/backends/ldap.py:337
#: keystone/assignment/backends/sql.py:243
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr ""

#: keystone/assignment/V8_backends/sql.py:363
#: keystone/assignment/backends/sql.py:319
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/assignment/backends/ldap.py:144
msgid "Domain grants not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:316
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:322
#, python-format
msgid "Role %s not found"
msgstr ""

#: keystone/assignment/role_backends/ldap.py:70 keystone/catalog/core.py:148
#: keystone/common/ldap/core.py:1408 keystone/resource/backends/ldap.py:168
#, python-format
msgid "Duplicate ID, %s."
msgstr ""

#: keystone/assignment/role_backends/ldap.py:85
#: keystone/common/ldap/core.py:1397
#, python-format
msgid "Duplicate name, %s."
msgstr ""

#: keystone/assignment/role_backends/ldap.py:135
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/auth/controllers.py:60
#, python-format
msgid ""
"Direct import of auth plugin %(name)r is deprecated as of Liberty in "
"favor of its entrypoint from %(namespace)r and may be removed in N."
msgstr ""

#: keystone/auth/controllers.py:121
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has "
"conflicting values %(new)s and %(old)s"
msgstr ""

#: keystone/auth/controllers.py:347 keystone/middleware/auth.py:86
msgid "Scoping to both domain and project is not allowed"
msgstr ""

#: keystone/auth/controllers.py:350
msgid "Scoping to both domain and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:353
msgid "Scoping to both project and trust is not allowed"
msgstr ""

#: keystone/auth/controllers.py:522
msgid "User not found"
msgstr ""

#: keystone/auth/controllers.py:626
msgid "A project-scoped token is required to produce a service catalog."
msgstr ""

#: keystone/auth/plugins/external.py:42
msgid "No authenticated user"
msgstr ""

#: keystone/auth/plugins/external.py:52
#, python-format
msgid "Unable to lookup user %s"
msgstr ""

#: keystone/auth/plugins/external.py:100
msgid "auth_type is not Negotiate"
msgstr ""

#: keystone/auth/plugins/mapped.py:236
msgid ""
"Could not map user while setting ephemeral user identity. Either mapping "
"rules must specify user id/name or REMOTE_USER environment variable must "
"be set."
msgstr ""

#: keystone/auth/plugins/oauth1.py:46
msgid "Access token is expired"
msgstr ""

#: keystone/auth/plugins/oauth1.py:60
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:39
msgid "Invalid username or password"
msgstr ""

#: keystone/auth/plugins/token.py:70 keystone/token/controllers.py:160
msgid "rescope a scoped token"
msgstr ""

#: keystone/catalog/controllers.py:215
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/catalog/backends/sql.py:392
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr ""

#: keystone/catalog/backends/sql.py:503
msgid "Endpoint Group Project Association not found"
msgstr ""

#: keystone/cmd/cli.py:123
msgid "Either --bootstrap-password argument or OS_BOOTSTRAP_PASSWORD must be set."
msgstr ""

#: keystone/cmd/cli.py:441
msgid "At least one option must be provided"
msgstr ""

#: keystone/cmd/cli.py:448
msgid "--all option cannot be mixed with other options"
msgstr ""

#: keystone/cmd/cli.py:455
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr ""

#: keystone/cmd/cli.py:510 keystone/tests/unit/test_cli.py:283
msgid "At least one option must be provided, use either --all or --domain-name"
msgstr ""

#: keystone/cmd/cli.py:516 keystone/tests/unit/test_cli.py:299
msgid "The --all option cannot be used with the --domain-name option"
msgstr ""

#: keystone/cmd/cli.py:541 keystone/tests/unit/test_cli.py:316
#, python-format
msgid ""
"Invalid domain name: %(domain)s found in config file name: %(file)s - "
"ignoring this file."
msgstr ""

#: keystone/cmd/cli.py:549 keystone/tests/unit/test_cli.py:257
#, python-format
msgid ""
"Domain: %(domain)s already has a configuration defined - ignoring file: "
"%(file)s."
msgstr ""

#: keystone/cmd/cli.py:563
#, python-format
msgid "Error parsing configuration file for domain: %(domain)s, file: %(file)s."
msgstr ""

#: keystone/cmd/cli.py:596
#, python-format
msgid ""
"To get a more detailed information on this error, re-run this command for"
" the specific domain, i.e.: keystone-manage domain_config_upload "
"--domain-name %s"
msgstr ""

#: keystone/cmd/cli.py:614
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr ""

#: keystone/cmd/cli.py:647
msgid ""
"Unable to access the keystone database, please check it is configured "
"correctly."
msgstr ""

#: keystone/cmd/cli.py:710
#, python-format
msgid "Error while parsing rules %(path)s: %(err)s"
msgstr ""

#: keystone/cmd/cli.py:719
#, python-format
msgid "Error while opening file %(path)s: %(err)s"
msgstr ""

#: keystone/cmd/cli.py:729
#, python-format
msgid "Error while parsing line: '%(line)s': %(err)s"
msgstr ""

#: keystone/common/authorization.py:61 keystone/common/wsgi.py:66
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr ""

#: keystone/common/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr ""

#: keystone/common/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr ""

#: keystone/common/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr ""

#: keystone/common/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr ""

#: keystone/common/controller.py:331 keystone/common/controller.py:359
#: keystone/identity/core.py:585 keystone/resource/core.py:915
#: keystone/resource/backends/ldap.py:64 keystone/resource/backends/ldap.py:72
#, python-format
msgid "Expected dict or list: %s"
msgstr ""

#: keystone/common/controller.py:372
msgid "Marker could not be found"
msgstr ""

#: keystone/common/controller.py:383
msgid "Invalid limit value"
msgstr ""

#: keystone/common/controller.py:687
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/controller.py:731
msgid ""
"You have tried to create a resource using the admin token. As this token "
"is not within a domain you must explicitly include a domain for this "
"resource to belong to."
msgstr ""

#: keystone/common/dependency.py:65
#, python-format
msgid "Unregistered dependency: %(name)s for %(targets)s"
msgstr ""

#: keystone/common/driver_hints.py:38
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/json_home.py:76
#, python-format
msgid "Unexpected status requested for JSON Home response, %s"
msgstr ""

#: keystone/common/manager.py:77
#, python-format
msgid ""
"Direct import of driver %(name)r is deprecated as of Liberty in favor of "
"its entrypoint from %(namespace)r and may be removed in N."
msgstr ""

#: keystone/common/tokenless_auth.py:73
msgid "Neither Project Domain ID nor Project Domain Name was provided."
msgstr ""

#: keystone/common/tokenless_auth.py:165
msgid ""
"User auth cannot be built due to missing either user id, or user name "
"with domain id, or user name with domain name."
msgstr ""

#: keystone/common/utils.py:168 keystone/credential/controllers.py:44
msgid "Invalid blob in credential"
msgstr ""

#: keystone/common/wsgi.py:205
msgid "Query string is not UTF-8 encoded"
msgstr ""

#: keystone/common/wsgi.py:341
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:353
#, python-format
msgid "%s field(s) cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:542
msgid "The resource could not be found."
msgstr ""

#: keystone/common/cache/_memcache_pool.py:126
#, python-format
msgid "Unable to get a connection from pool id %(id)s after %(seconds)s seconds."
msgstr ""

#: keystone/common/kvs/core.py:87
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:122
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:161
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:214
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:370
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:374
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:68
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:109
#, python-format
msgid ""
"Backend `%(backend)s` is not a valid memcached backend. Valid backends: "
"%(backend_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:185
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:196
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:206
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:218
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:588
msgid "Invalid TLS / LDAPS combination"
msgstr ""

#: keystone/common/ldap/core.py:593
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr ""

#: keystone/common/ldap/core.py:603
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr ""

#: keystone/common/ldap/core.py:615
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr ""

#: keystone/common/ldap/core.py:1330
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr ""

#: keystone/common/ldap/core.py:1375
#, python-format
msgid "LDAP %s create"
msgstr ""

#: keystone/common/ldap/core.py:1380
#, python-format
msgid "LDAP %s update"
msgstr ""

#: keystone/common/ldap/core.py:1385
#, python-format
msgid "LDAP %s delete"
msgstr ""

#: keystone/common/ldap/core.py:1554
msgid ""
"Disabling an entity where the 'enable' attribute is ignored by "
"configuration."
msgstr ""

#: keystone/common/ldap/core.py:1565
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr ""

#: keystone/common/ldap/core.py:1652
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr ""

#: keystone/common/sql/core.py:409
msgid "Duplicate Entry"
msgstr ""

#: keystone/common/sql/core.py:425
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr ""

#: keystone/common/sql/migration_helpers.py:175
#: keystone/common/sql/migration_helpers.py:217
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/common/validation/__init__.py:45
#, python-format
msgid ""
"validated expected to find %(param_name)r in function signature for "
"%(func_name)r."
msgstr ""

#: keystone/common/validation/validators.py:54
#, python-format
msgid "Invalid input for field '%(path)s'. The value is '%(value)s'."
msgstr ""

#: keystone/contrib/ec2/controllers.py:80 keystone/contrib/s3/core.py:111
#: keystone/contrib/s3/core.py:114
msgid "Invalid EC2 signature."
msgstr ""

#: keystone/contrib/ec2/controllers.py:83
#: keystone/contrib/ec2/controllers.py:87
#: keystone/contrib/ec2/controllers.py:125
msgid "EC2 signature not supplied."
msgstr ""

#: keystone/contrib/ec2/controllers.py:159
msgid "User not valid for tenant."
msgstr ""

#: keystone/contrib/ec2/controllers.py:260
msgid "EC2 access key not found."
msgstr ""

#: keystone/contrib/ec2/controllers.py:326
msgid "Token belongs to another user"
msgstr ""

#: keystone/contrib/ec2/controllers.py:354
msgid "Credential belongs to another user"
msgstr ""

#: keystone/contrib/endpoint_filter/routers.py:29
msgid ""
"Remove endpoint_filter_extension from the paste pipeline, the endpoint "
"filter extension is now always available. Update the [pipeline:api_v3] "
"section in keystone-paste.ini accordingly as it will be removed in the O "
"release."
msgstr ""

#: keystone/contrib/federation/routers.py:27
msgid ""
"Remove federation_extension from the paste pipeline, the federation "
"extension is now always available. Update the [pipeline:api_v3] section "
"in keystone-paste.ini accordingly, as it will be removed in the O "
"release."
msgstr ""

#: keystone/contrib/oauth1/routers.py:29
msgid ""
"Remove oauth1_extension from the paste pipeline, the oauth1 extension is "
"now always available. Update the [pipeline:api_v3] section in keystone-"
"paste.ini accordingly, as it will be removed in the O release."
msgstr ""

#: keystone/contrib/revoke/routers.py:27
msgid ""
"Remove revoke_extension from the paste pipeline, the revoke extension is "
"now always available. Update the [pipeline:api_v3] section in keystone-"
"paste.ini accordingly, as it will be removed in the O release."
msgstr ""

#: keystone/contrib/s3/core.py:82
msgid "Credential signature mismatch"
msgstr ""

#: keystone/endpoint_policy/core.py:264
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr ""

#: keystone/federation/controllers.py:267
msgid "Request must have an origin query parameter"
msgstr ""

#: keystone/federation/controllers.py:272
#, python-format
msgid "%(host)s is not a trusted dashboard host"
msgstr ""

#: keystone/federation/controllers.py:303
msgid "Missing entity ID from environment"
msgstr ""

#: keystone/federation/controllers.py:351
msgid "Use a project scoped token when attempting to create a SAML assertion"
msgstr ""

#: keystone/federation/idp.py:486
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr ""

#: keystone/federation/idp.py:552
msgid "Ensure configuration option idp_entity_id is set."
msgstr ""

#: keystone/federation/idp.py:555
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr ""

#: keystone/federation/idp.py:574
msgid ""
"idp_contact_type must be one of: [technical, other, support, "
"administrative or billing."
msgstr ""

#: keystone/federation/utils.py:177
msgid "Federation token is expired"
msgstr ""

#: keystone/federation/utils.py:229
msgid "Could not find Identity Provider identifier in environment"
msgstr ""

#: keystone/federation/utils.py:233
msgid ""
"Incoming identity provider identifier not included among the accepted "
"identifiers."
msgstr ""

#: keystone/federation/utils.py:524
#, python-format
msgid "User type %s not supported"
msgstr ""

#: keystone/federation/utils.py:559
#, python-format
msgid ""
"Invalid rule: %(identity_value)s. Both 'groups' and 'domain' keywords "
"must be specified."
msgstr ""

#: keystone/federation/utils.py:777
#, python-format
msgid "Identity Provider %(idp)s is disabled"
msgstr ""

#: keystone/federation/utils.py:785
#, python-format
msgid "Service Provider %(sp)s is disabled"
msgstr ""

#: keystone/federation/backends/sql.py:182
#, python-format
msgid "Duplicate remote ID: %s"
msgstr ""

#: keystone/federation/backends/sql.py:184
#, python-format
msgid "Duplicate entry: %s"
msgstr ""

#: keystone/identity/controllers.py:74
msgid "Enabled field must be a boolean"
msgstr ""

#: keystone/identity/controllers.py:101
msgid "Enabled field should be a boolean"
msgstr ""

#: keystone/identity/core.py:261
#, python-format
msgid "Config API entity at /domains/%s/config"
msgstr ""

#: keystone/identity/core.py:267
#, python-format
msgid ""
"Exceeded attempts to register domain %(domain)s to use the SQL driver, "
"the last domain that appears to have had it is %(last_domain)s, giving up"
msgstr ""

#: keystone/identity/core.py:440 keystone/identity/backends/ldap.py:58
#: keystone/identity/backends/ldap.py:60 keystone/identity/backends/ldap.py:66
#: keystone/identity/backends/ldap.py:68 keystone/identity/backends/sql.py:106
#: keystone/identity/backends/sql.py:108
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/core.py:850
#, python-format
msgid "User is disabled: %s"
msgstr ""

#: keystone/identity/core.py:892
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/ldap.py:98
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:187 keystone/identity/backends/sql.py:190
#: keystone/identity/backends/sql.py:208
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr ""

#: keystone/identity/backends/ldap.py:338
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr ""

#: keystone/models/token_model.py:61
msgid "Found invalid token: scoped to both project and domain."
msgstr ""

#: keystone/oauth1/controllers.py:95
msgid "Cannot change consumer secret"
msgstr ""

#: keystone/oauth1/controllers.py:127
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""

#: keystone/oauth1/controllers.py:188 keystone/oauth1/backends/sql.py:270
msgid "User IDs do not match"
msgstr ""

#: keystone/oauth1/controllers.py:244
msgid "Invalid signature"
msgstr ""

#: keystone/oauth1/controllers.py:295 keystone/oauth1/controllers.py:373
msgid "Request token is expired"
msgstr ""

#: keystone/oauth1/controllers.py:309
msgid "There should not be any non-oauth parameters"
msgstr ""

#: keystone/oauth1/controllers.py:313
msgid "provided consumer key does not match stored consumer key"
msgstr ""

#: keystone/oauth1/controllers.py:317
msgid "provided verifier does not match stored verifier"
msgstr ""

#: keystone/oauth1/controllers.py:321
msgid "provided request key does not match stored request key"
msgstr ""

#: keystone/oauth1/controllers.py:325
msgid "Request Token does not have an authorizing user id"
msgstr ""

#: keystone/oauth1/controllers.py:362
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""

#: keystone/oauth1/controllers.py:389
msgid "authorizing user does not have role required"
msgstr ""

#: keystone/oauth1/controllers.py:402
msgid "User is not a member of the requested project"
msgstr ""

#: keystone/oauth1/backends/sql.py:91
msgid "Consumer not found"
msgstr ""

#: keystone/oauth1/backends/sql.py:186
msgid "Request token not found"
msgstr ""

#: keystone/oauth1/backends/sql.py:250
msgid "Access token not found"
msgstr ""

#: keystone/resource/controllers.py:233
msgid "The creation of projects acting as domains is not allowed yet."
msgstr ""

#: keystone/resource/controllers.py:267
msgid ""
"Cannot use parents_as_list and parents_as_ids query params at the same "
"time."
msgstr ""

#: keystone/resource/controllers.py:273
msgid ""
"Cannot use subtree_as_list and subtree_as_ids query params at the same "
"time."
msgstr ""

#: keystone/resource/core.py:90
#, python-format
msgid "max hierarchy depth reached for %s branch."
msgstr ""

#: keystone/resource/core.py:108 keystone/resource/core.py:509
msgid "Multiple domains are not supported"
msgstr ""

#: keystone/resource/core.py:114
msgid "only root projects are allowed to act as domains."
msgstr ""

#: keystone/resource/core.py:138
#, python-format
msgid ""
"Cannot create project, since it specifies its owner as domain "
"%(domain_id)s, but specifies a parent in a different domain "
"(%(parent_domain_id)s)."
msgstr ""

#: keystone/resource/core.py:163
#, python-format
msgid "cannot create a project in a branch containing a disabled project: %s"
msgstr ""

#: keystone/resource/core.py:171
#, python-format
msgid ""
"%(entity)s name cannot contain the following reserved characters: "
"%(chars)s"
msgstr ""

#: keystone/resource/core.py:222
#, python-format
msgid "Domain is disabled: %s"
msgstr ""

#: keystone/resource/core.py:239
#, python-format
msgid "Domain cannot be named %s"
msgstr ""

#: keystone/resource/core.py:242
#, python-format
msgid "Domain cannot have ID %s"
msgstr ""

#: keystone/resource/core.py:254
#, python-format
msgid "Project is disabled: %s"
msgstr ""

#: keystone/resource/core.py:274
#, python-format
msgid "cannot enable project %s since it has disabled parents"
msgstr ""

#: keystone/resource/core.py:282
#, python-format
msgid "cannot disable project %s since its subtree contains enabled projects"
msgstr ""

#: keystone/resource/core.py:300
msgid "Update of `parent_id` is not allowed."
msgstr ""

#: keystone/resource/core.py:305
msgid "Update of `is_domain` is not allowed."
msgstr ""

#: keystone/resource/core.py:341
#, python-format
msgid ""
"cannot delete an enabled project acting as a domain. Please disable the "
"project %s first."
msgstr ""

#: keystone/resource/core.py:347
#, python-format
msgid "cannot delete the project %s since it is not a leaf in the hierarchy."
msgstr ""

#: keystone/resource/core.py:373
msgid "Project field is required and cannot be empty."
msgstr ""

#: keystone/resource/core.py:576
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/resource/core.py:1114
msgid "No options specified"
msgstr ""

#: keystone/resource/core.py:1120
#, python-format
msgid ""
"The value of group %(group)s specified in the config should be a "
"dictionary of options"
msgstr ""

#: keystone/resource/core.py:1144
#, python-format
msgid ""
"Option %(option)s found with no group specified while checking domain "
"configuration request"
msgstr ""

#: keystone/resource/core.py:1151
#, python-format
msgid "Group %(group)s is not supported for domain specific configurations"
msgstr ""

#: keystone/resource/core.py:1158
#, python-format
msgid ""
"Option %(option)s in group %(group)s is not supported for domain specific"
" configurations"
msgstr ""

#: keystone/resource/core.py:1210
msgid "An unexpected error occurred when retrieving domain configs"
msgstr ""

#: keystone/resource/core.py:1289 keystone/resource/core.py:1372
#: keystone/resource/core.py:1442 keystone/resource/config_backends/sql.py:76
#, python-format
msgid "option %(option)s in group %(group)s"
msgstr ""

#: keystone/resource/core.py:1292 keystone/resource/core.py:1377
#: keystone/resource/core.py:1438
#, python-format
msgid "group %(group)s"
msgstr ""

#: keystone/resource/core.py:1294
msgid "any options"
msgstr ""

#: keystone/resource/core.py:1337
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, so that, and only "
"that, option must be specified  in the config"
msgstr ""

#: keystone/resource/core.py:1342
#, python-format
msgid ""
"Trying to update group %(group)s, so that, and only that, group must be "
"specified in the config"
msgstr ""

#: keystone/resource/core.py:1351
#, python-format
msgid ""
"request to update group %(group)s, but config provided contains group "
"%(group_other)s instead"
msgstr ""

#: keystone/resource/core.py:1358
#, python-format
msgid ""
"Trying to update option %(option)s in group %(group)s, but config "
"provided contains option %(option_other)s instead"
msgstr ""

#: keystone/resource/core.py:1550
#, python-format
msgid "Group  %s not found in config"
msgstr ""

#: keystone/resource/core.py:1560
#, python-format
msgid ""
"Reading the default for option %(option)s in group %(group)s is not "
"supported"
msgstr ""

#: keystone/resource/backends/ldap.py:86
msgid "LDAP does not support projects with is_domain flag enabled"
msgstr ""

#: keystone/resource/backends/ldap.py:170
#: keystone/resource/backends/ldap.py:178
#: keystone/resource/backends/ldap.py:182
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/revoke/core.py:156
msgid ""
"The revoke call must not have both domain_id and project_id. This is a "
"bug in the Keystone server. The current request is aborted."
msgstr ""

#: keystone/revoke/core.py:224 keystone/token/provider.py:217
#: keystone/token/provider.py:241 keystone/token/provider.py:310
#: keystone/token/provider.py:317
msgid "Failed to validate token"
msgstr ""

#: keystone/server/eventlet.py:77
msgid ""
"Running keystone via eventlet is deprecated as of Kilo in favor of "
"running in a WSGI server (e.g. mod_wsgi). Support for keystone under "
"eventlet will be removed in the \"M\"-Release."
msgstr ""

#: keystone/server/eventlet.py:90
#, python-format
msgid "Failed to start the %(name)s server"
msgstr ""

#: keystone/token/controllers.py:388
#, python-format
msgid "Project ID not found: %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:392
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr ""

#: keystone/token/controllers.py:411 keystone/token/controllers.py:414
msgid "Token does not belong to specified tenant."
msgstr ""

#: keystone/token/provider.py:254 keystone/token/provider.py:273
msgid "No token in the request"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/providers/common.py:286
#: keystone/token/providers/common.py:391
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr ""

#: keystone/token/providers/common.py:291
#: keystone/token/providers/common.py:396
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr ""

#: keystone/token/providers/common.py:318
msgid "Trustor is disabled."
msgstr ""

#: keystone/token/providers/common.py:382
msgid "Trustee has no delegated roles."
msgstr ""

#: keystone/token/providers/common.py:442
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr ""

#: keystone/token/providers/common.py:528
msgid "The configured token provider does not support bind authentication."
msgstr ""

#: keystone/token/providers/common.py:539
msgid "User is not a trustee."
msgstr ""

#: keystone/token/providers/common.py:606
msgid ""
"Attempting to use OS-FEDERATION token with V2 Identity Service, use V3 "
"Authentication"
msgstr ""

#: keystone/token/providers/common.py:616
msgid "Non-default domain is not supported"
msgstr ""

#: keystone/token/providers/common.py:620
msgid "Domain scoped token is not supported"
msgstr ""

#: keystone/token/providers/pki.py:53 keystone/token/providers/pkiz.py:31
msgid "Unable to sign token."
msgstr ""

#: keystone/token/providers/fernet/core.py:216
msgid ""
"This is not a v2.0 Fernet token. Use v3 for trust, domain, or federated "
"tokens."
msgstr ""

#: keystone/token/providers/fernet/token_formatters.py:102
msgid "This is not a recognized Fernet token"
msgstr ""

#: keystone/token/providers/fernet/token_formatters.py:197
#, python-format
msgid "This is not a recognized Fernet payload version: %s"
msgstr ""

#: keystone/trust/controllers.py:111
#, python-format
msgid "role %s is not defined"
msgstr ""

#: keystone/trust/controllers.py:135
msgid "Redelegation allowed for delegated by trust only"
msgstr ""

#: keystone/trust/controllers.py:168
msgid "The authenticated user should match the trustor."
msgstr ""

#: keystone/trust/controllers.py:173
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:58
#, python-format
msgid ""
"Remaining redelegation depth of %(redelegation_depth)d out of allowed "
"range of [0..%(max_count)d]"
msgstr ""

#: keystone/trust/core.py:67
#, python-format
msgid ""
"Field \"remaining_uses\" is set to %(value)s while it must not be set in "
"order to redelegate a trust"
msgstr ""

#: keystone/trust/core.py:78
msgid "Requested expiration time is more than redelegated trust can provide"
msgstr ""

#: keystone/trust/core.py:88
msgid "Some of requested roles are not in redelegated trust"
msgstr ""

#: keystone/trust/core.py:117
msgid "One of the trust agents is disabled or deleted"
msgstr ""

#: keystone/trust/core.py:136
msgid "remaining_uses must be a positive integer or null."
msgstr ""

#: keystone/trust/core.py:142
#, python-format
msgid ""
"Requested redelegation depth of %(requested_count)d is greater than "
"allowed %(max_count)d"
msgstr ""

#: keystone/trust/core.py:149
msgid "remaining_uses must not be set if redelegation is allowed"
msgstr ""

#: keystone/trust/core.py:159
msgid ""
"Modifying \"redelegation_count\" upon redelegation is forbidden. Omitting"
" this parameter is advised."
msgstr ""

